version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - 15672:15672
      - 5672:5672
    hostname: rbq
  receiver:
    build: ./receiver
    depends_on:
      - rabbitmq
    ports:
      - 8082:8082
    environment:
      - spring.rabbitmq.host=rbq
  sender:
    build: ./sender
    depends_on:
      - rabbitmq
    ports:
      - 8081:8081
    environment:
      - spring.rabbitmq.host=rbq